prj_name = "gdemo"
idc = ""

[log]
[log.api]
path = ""
level = 6
async_queue_size = 1000000
bufsize = 4096
formater = "json"
enable_color = false

[pprof]
enable = false
port = 6060

[api]
host = "127.0.0.1"
port = 9001
enable_sign = true

[redis]
host = ""
pass = ""
port = 0
connect_timeout_seconds = 3
rw_timeout_seconds = 3
pool_size = 256
pool_keepalive_interval_seconds = 10
pool_client_max_idle_seconds = 30

[mysql]
host = ""
user = ""
pass = ""
port = 0
name = "gobox-demo"
rw_timeout_seconds = 3

[tracing]
enable = true
target = "zipkin"
async = true
service_namespace = "release"
zipkin_url = ""

[misc]
apps_data_dir = ""

