is_dev = true
idc = "dev"

[log]
[log.api]
path = "/dev/stdout"
level = 7
async_queue_size = 0
bufsize = 0
formater = "simple"
enable_color = true


[pprof]
enable = true
port = ${PPROF_PORT}

[api]
port = ${API_GOHTTP_PORT}
pid_file = "${PRJ_HOME}/tmp/api.pid"

[redis]
host = "127.0.0.1"
pass = "123"
port = 6379


[mysql]
host = "127.0.0.1"
user = "root"
pass = "123"
port = 3306
