idc = "dev"

[log]
[log.api]
path = "/dev/stdout"
level = 7
async_queue_size = 0
bufsize = 0
formater = "simple"
enable_color = true


[redis]
host = "127.0.0.1"
pass = "123"
port = 6379


[mysql]
host = "127.0.0.1"
user = "root"
pass = "123"
port = 13306

[tracing]
async = false
service_namespace = "dev"
zipkin_url = "http://tdev.gibsonli.com:9411/api/v2/spans"


[misc]
apps_data_dir = "${APPS_DATA_DIR}"